apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
