---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-3
  labels:
    name: nginx-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:
        app: nginx-3
    spec:
      containers:
        - name: nginx3
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-3-myapp
  labels:
    app: nginx-3
spec:
  type: ClusterIP
  selector:
    app: nginx-3
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP