---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
  labels:
    name: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
        - name: nginx2
          image: fadhiljr/kube-nginxapp2:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-2-myapp
  labels:
    app: nginx-2
spec:
  type: ClusterIP
  selector:
    app: nginx-2
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP