apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: fadhilahamed07@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-letsencrypt-key
    solvers:
     - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token