---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  labels:
    name: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
        - name: nginx1
          image: fadhiljr/kube-nginxapp1:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-myapp
  labels:
    app: nginx-1
spec:
  type: ClusterIP
  selector:
    app: nginx-1
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP