apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-app
  template:
    metadata:
      labels:
        app: usermgmt-app
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
       - name: usermgmt-app
         image: fadhiljr/user-mgmt-1:1.0
         imagePullPolicy: Always
         ports:
          - containerPort: 8080
         env:
          - name: DB_HOSTNAME
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "webappdb"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            value: "dbpassword11"
